#define CHARM_CPU x86_64
#define CHARM_HOST_CPU x86_64
#define CHARM_OS linux
#define CHARM_PLATFORM mpi-crayshasta
#define CHARM_VERSION 70000
#define CMK_AMPI_ONLY 0
#define CMK_AMPI_WITH_ROMIO 1
#define CMK_BALANCED_INJECTION_API 0
#define CMK_BUILD_CHARMRUN 0
#define CMK_BUILD_CRAY 0
#define CMK_BUILD_MPI 0
#define CMK_BUILD_OFI 0
#define CMK_BUILD_ON_MPI 0
#define CMK_BUILD_ON_UCX 0
#define CMK_BUILD_PYTHON 2.7
#define CMK_CAN_GET_BINARY_PATH 1
#define CMK_CAN_LINK_FORTRAN 1
#define CMK_CAN_OPEN_SHARED_OBJECTS_DYNAMICALLY 1
#define CMK_CCS_AVAILABLE 1
#define CMK_CHARM4PY 0
#define CMK_CHARMDEBUG 0
#define CMK_CKSECTIONINFO_STL 1
#define CMK_COMPILER clang
#define CMK_COMPILER_KNOWS_FNOSTACKPROTECTOR 1
#define CMK_COMPILER_KNOWS_FNOSTACKPROTECTOR 1
#define CMK_COMPILER_KNOWS_FTLS_MODEL 1
#define CMK_COMPILER_KNOWS_FTLS_MODEL 1
#define CMK_COMPILER_KNOWS_FVISIBILITY 1
#define CMK_COMPILER_KNOWS_FVISIBILITY 1
#define CMK_COMPILER_KNOWS_LIFETIMEDSE 0
#define CMK_COMPILER_KNOWS_LIFETIMEDSE 0
#define CMK_COMPILER_KNOWS_RDYNAMIC 1
#define CMK_COMPILER_KNOWS_RDYNAMIC 1
#define CMK_COMPILER_KNOWS_TLSDIRECTSEGREFS 1
#define CMK_COMPILER_KNOWS_TLSDIRECTSEGREFS 1
#define CMK_CONTEXT_FPU_POINTER 1
#define CMK_CONTEXT_FPU_POINTER_UCREGS 0
#define CMK_CONTEXT_V_REGS 0
#define CMK_CXX_MPI_BINDINGS 1
#define CMK_C_INLINE 1
#define CMK_C_SYNC_ADD_AND_FETCH_PRIMITIVE 1
#define CMK_C_SYNC_SYNCHRONIZE_PRIMITIVE 1
#define CMK_DLL_USE_DLOPEN 1
#define CMK_DLL_USE_WIN32 0
#define CMK_DRONE_MODE 0
#define CMK_ERROR_CHECKING 0
#define CMK_EXPECTS_MORECORE 1
#define CMK_FORTRAN_USES_ALLCAPS 0
#define CMK_FORTRAN_USES_NOSCORE 0
#define CMK_FORTRAN_USES_ONESCORE 1
#define CMK_FORTRAN_USES_TWOSCORE 0
#define CMK_GCC_X86_ASM 1
#define CMK_GCC_X86_ASM_ATOMICINCREMENT 1
#define CMK_HAS_ADDR_NO_RANDOMIZE 1
#define CMK_HAS_ALIGNMENT_OF 1
#define CMK_HAS_ALLOCA_H 1
#define CMK_HAS_ASCTIME 1
#define CMK_HAS_ATTRIBUTE_VISIBILITY_DEFAULT 1
#define CMK_HAS_BINDPROCESSOR 0
#define CMK_HAS_CFREE 0
#define CMK_HAS_CMA 1
#define CMK_HAS_COUNTER_PAPI 0
#define CMK_HAS_CXX0X_CSTDATOMIC 0
#define CMK_HAS_CXX11_ATOMIC 1
#define CMK_HAS_DLMOPEN 1
#define CMK_HAS_DLOPEN 1
#define CMK_HAS_DL_ITERATE_PHDR 1
#define CMK_HAS_ELF_H 1
#define CMK_HAS_EXECUTABLE_START 1
#define CMK_HAS_FABSF 1
#define CMK_HAS_FDATASYNC_FUNC 1
#define CMK_HAS_FSYNC_FUNC 1
#define CMK_HAS_GETIFADDRS 1
#define CMK_HAS_GETPAGESIZE 1
#define CMK_HAS_GETPID 1
#define CMK_HAS_GET_MYADDRESS 1
#define CMK_HAS_INT16 16
#define CMK_HAS_IO_FILE_OVERFLOW 1
#define CMK_HAS_IS_CONSTRUCTIBLE 1
#define CMK_HAS_ITERATOR_TRAITS 1
#define CMK_HAS_KILL 1
#define CMK_HAS_LOG2 1
#define CMK_HAS_LUSTREFS 0
#define CMK_HAS_MALLINFO 1
#define CMK_HAS_MALLOC_H 1
#define CMK_HAS_MMAP 1
#define CMK_HAS_MMAP_ANON 1
#define CMK_HAS_MMAP_NORESERVE 1
#define CMK_HAS_MPROTECT 1
#define CMK_HAS_MSTATS 0
#define CMK_HAS_MULTIPROCESSING_H 0
#define CMK_HAS_NTOHL 1
#define CMK_HAS_NUMACTRL 0
#define CMK_HAS_OFFSETOF 1
#define CMK_HAS_OPENMP 1
#define CMK_HAS_PMI_GET_NID 1
#define CMK_HAS_POPEN 1
#define CMK_HAS_POSIX_SPAWN 1
#define CMK_HAS_PTHREAD_SETAFFINITY 1
#define CMK_HAS_PVALLOC 1
#define CMK_HAS_PYTHON 1
#define CMK_HAS_RCALIB 1
#define CMK_HAS_RCA_MAX_DIMENSION 1
#define CMK_HAS_READLINK 1
#define CMK_HAS_REALPATH 1
#define CMK_HAS_REGEX 1
#define CMK_HAS_REGEX_H 1
#define CMK_HAS_RTLD_DEEPBIND 1
#define CMK_HAS_RTLD_DEFAULT 1
#define CMK_HAS_RTLD_NEXT 1
#define CMK_HAS_RUSAGE_THREAD 1
#define CMK_HAS_SBRK 1
#define CMK_HAS_SETAFFINITY 1
#define CMK_HAS_SETPRIORITY 1
#define CMK_HAS_SLEEP 1
#define CMK_HAS_SOCKLEN 4
#define CMK_HAS_SPINLOCK 1
#define CMK_HAS_SQRTF 1
#define CMK_HAS_STDINT_H 1
#define CMK_HAS_STD_DISTANCE 1
#define CMK_HAS_STD_INSERTER 1
#define CMK_HAS_STD_VOID_T 0
#define CMK_HAS_STRINGS_H 1
#define CMK_HAS_SYNC 1
#define CMK_HAS_SYNC_FUNC 1
#define CMK_HAS_SYSTEM 1
#define CMK_HAS_TLS_VARIABLES 1
#define CMK_HAS_TYPEINFO 1
#define CMK_HAS_UNDERSCORE_SETJMP 1
#define CMK_HAS_USLEEP 1
#define CMK_HAS_VALLOC 1
#define CMK_HAS_VALUES_H 1
#define CMK_HAS_XPMEM 0
#define CMK_IBV_PORT_ATTR_HAS_LINK_LAYER 0
#define CMK_LBID_64BIT 1
#define CMK_LBTIME_TYPE double
#define CMK_LB_USER_DATA 0
#define CMK_LIBJPEG -ljpeg
#define CMK_LINKER_KNOWS_EXPORT_DYNAMIC 1
#define CMK_LINKER_KNOWS_EXPORT_DYNAMIC 1
#define CMK_LINKER_KNOWS_UNDEFINED 1
#define CMK_LINKER_KNOWS_UNDEFINED 1
#define CMK_LOCKLESS_QUEUE 0
#define CMK_LONG_DOUBLE_DEFINED 16
#define CMK_LONG_LONG_DEFINED 8
#define CMK_MACHINE_NAME "mpi-crayshasta"
#define CMK_MACOSX 0
#define CMK_MEMPOOL_CUTOFFNUM 26
#define CMK_MOD_EXT mod
#define CMK_MOD_NAME_ALLCAPS 0
#define CMK_MSG_PRIO_TYPE bitvec
#define CMK_MULTICORE 0
#define CMK_MULTIPLE_DELETE 1
#define CMK_NO_PARTITIONS 0
#define CMK_OPTIMIZE 1
#define CMK_OS_IS_LINUX 1
#define CMK_POST_EXE 0
#define CMK_PPC_ASM 0
#define CMK_PYTHON_VERSION 2.7
#define CMK_RANDOMIZED_MSGQ 0
#define CMK_REFNUM_TYPE unsigned short
#define CMK_REPLAYSYSTEM 0
#define CMK_SHARED_SUF so
#define CMK_SHRINK_EXPAND 0
#define CMK_SIGNEDCHAR_DIFF_CHAR 1
#define CMK_SIGSAFE_SYSTEM 1
#define CMK_SIZET_64BIT 1
#define CMK_SMP 1
#define CMK_SMP_TRACE_COMMTHREAD 0
#define CMK_SUPPORTS_FSGLOBALS 1
#define CMK_SUPPORTS_MEMORY_ISOMALLOC 1
#define CMK_SUPPORTS_PIEGLOBALS 1
#define CMK_SUPPORTS_PIPGLOBALS 1
#define CMK_SUPPORTS_SWAPGLOBALS 0
#define CMK_SUPPORTS_TLSGLOBALS 1
#define CMK_SYSLIBS $CMK_SYSLIBS  -lz
#define CMK_TASKQUEUE 0
#define CMK_TRACE_ENABLED 0
#define CMK_USER_SUFFIX .user
#define CMK_USE_BACKTRACE 1
#define CMK_USE_LIBJPEG 1
#define CMK_USE_LRTS 1
#define CMK_USE_MKSTEMP 1
#define CMK_USE_POLL 1
#define CMK_USE_SHMEM 0
#define CMK_USE_STL_MSGQ 0
#define CMK_USE_ZLIB 1
#define CMK_WINDOWS 0
#define CMK_WITH_CONTROLPOINT 0
#define CMK_WITH_STATS 0
#define CMK___int128_DEFINED 16
#define CMK___int128_t_DEFINED 16
#define CMK___int64_DEFINED 0
/* #define HAVE_CLZ 0 */
/* #define HAVE_CLZL 0 */
#define HAVE_CMK_HAS_INT16 1
#define HAVE_CMK_HAS_SOCKLEN 1
/* #define HAVE_CMK_HAS_STD_VOID_T 0 */
#define HAVE_CMK_LONG_DOUBLE_DEFINED 1
#define HAVE_CMK_LONG_LONG_DEFINED 1
#define HAVE_CMK___int128_DEFINED 1
#define HAVE_CMK___int128_t_DEFINED 1
/* #define HAVE_CMK___int64_DEFINED 0 */
/* #define HAVE_CUDA_H 0 */
/* #define HAVE_DECL_GETEXECNAME 0 */
/* #define HAVE_DECL_GETPROGNAME 0 */
/* #define HAVE_FLS 0 */
/* #define HAVE_FLSL 0 */
/* #define HAVE_GROUP_AFFINITY 0 */
/* #define HAVE_GROUP_RELATIONSHIP 0 */
/* #define HAVE_HAVE_GROUP_AFFINITY 0 */
/* #define HAVE_HAVE_GROUP_RELATIONSHIP 0 */
/* #define HAVE_HAVE_KAFFINITY 0 */
#define HAVE_HAVE_PTHREAD_T 1
#define HAVE_HAVE_SSIZE_T 1
/* #define HAVE_HOST_INFO 0 */
/* #define HAVE_KAFFINITY 0 */
/* #define HAVE_KSTAT_H 0 */
/* #define HAVE_LIBUDEV_H 0 */
#define HAVE_MY_HAS_PID_T 1
/* #define HAVE_PTHREAD_NP_H 0 */
#define HAVE_SIZEOF_UNSIGNED_INT 1
#define HAVE_SIZEOF_UNSIGNED_LONG 1
#define HAVE_SIZEOF_VOID_P 1
/* #define HAVE_SYSCTLBYNAME 0 */
/* #define HAVE_SYS_CPUSET_H 0 */
/* #define HAVE_SYS_LGRP_USER_H 0 */
/* #define HAVE_VALGRIND_VALGRIND_H 0 */
/* #define HAVE__PUTENV 0 */
/* #define HAVE__STRDUP 0 */
#define HAVE_size_t_size 1
#define QLOGIC 0
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_VOID_P 8
