#!/bin/bash

#SBATCH --ntasks=8
#SBATCH --ntasks-per-socket=4
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --hint=nomultithread
#SBATCH -p icelake
#SBATCH --time=240
#SBATCH --distribution=block:block

#export FI_LOG_LEVEL=Info
#export OMP_NUM_THREADS=1

srun -n 8 -N 1 --cpu-bind=map_cpu:0,7,14,21,28,35,42,49 ./namd2-skl-ivdep +skip_cpu_topology +ppn 6 +pemap 1-6,8-13,15-20,22-27,29-34,36-41,43-48,50-55 +commap 0,7,14,21,28,35,42,49 +setcpuaffinity ./stmv.namd 
