#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --ntasks-per-socket=1
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --hint=nomultithread
#SBATCH -p castle
#SBATCH --time=240
#SBATCH --distribution=block:block

#export FI_LOG_LEVEL=Info
#export OMP_NUM_THREADS=1

srun -n 1 -N 1 -c 1 ./namd2-spr-ivdep ./stmv.namd 
